apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - hpa.yaml
  - role.yaml
  - serviceaccount.yaml

images:
  - name: us-docker.pkg.dev/grid-stream/gridstream/theo
    newTag: latest
