apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: theo-deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: theo-deployment-manager-binding
subjects:
- kind: ServiceAccount
  name: theo
roleRef:
  kind: Role
  name: theo-deployment-manager
  apiGroup: rbac.authorization.k8s.io