apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - hpa.yaml
  - service.yaml

images:
  - name: us-docker.pkg.dev/grid-stream/gridstream/validator
    newTag: latest