name: apply-manifests
on:
  push:
    branches: [ main ]
    paths:
      - 'versions.yaml'
      - 'k8s/**'

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACC_KEY }}"

      - name: Setup gcloud and Auth Plugin
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: "gke-gcloud-auth-plugin"

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GCP_GKE_CLUSTER }}
          location: ${{ secrets.GCP_REGION }}

      - name: Create Kubernetes Secrets
        run: |
          gcloud secrets versions access latest --secret=CREDS_PATH_SECRET \
            | kubectl create secret generic bigquery-credentials \
              -n gridstream-operations \
              --from-file=credentials.json=/dev/stdin \
              --dry-run=client -o yaml \
            | kubectl apply -n gridstream-operations -f -
            
          gcloud secrets versions access latest --secret=BATCHER_STREAM_CONFIG_SECRET \
            | kubectl create secret generic batcher-stream-config \
            -n gridstream-operations \
            --from-file=config.json=/dev/stdin \
            --dry-run=client -o yaml \
            | kubectl apply -n gridstream-operations -f -

      - name: Update and Apply All Manifests
        run: |
          chmod +x scripts/apply.sh
          scripts/apply.sh
